In [163]:
# Data Processing
import pandas as pd
import numpy as np
import datetime

# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint
from sklearn.preprocessing import MinMaxScaler

# Tree Visualisation
from sklearn.tree import export_graphviz
from IPython.display import Image
import graphviz

In [104]:
data=pd.read_csv("weatherHistory.csv")

In [105]:
data.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [106]:
data.drop('Loud Cover',axis=1)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,1016.16,Partly cloudy starting in the morning.

In [35]:
data.head(Daily Summary)

,Formatted Date,Summary,Precip Type,Humidity,Wind Bearing (degrees),Visibility (km),Wind Speed (km/h),Pressure (millibars),Daily Summary,Temperature (C),Apparent Temperature (C)
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,0.89,251.0,15.8263,14.1197,1015.13,Partly cloudy throughout the day.,9.472222,7.388889
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,0.86,259.0,15.8263,14.2646,1015.63,Partly cloudy throughout the day.,9.355556,7.227778
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,0.89,204.0,14.9569,3.9284,1015.94,Partly cloudy throughout the day.,9.377778,9.377778
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,0.83,269.0,15.8263,14.1036,1016.41,Partly cloudy throughout the day.,8.288889,5.944444
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,0.83,259.0,15.8263,11.0446,1016.51,Partly cloudy throughout the day.,8.755556,6.977778

In [107]:
le = LabelEncoder()
data["Summary"] = le.fit_transform(data["Summary"])
data["Precip Type"] = le.fit_transform(data["Precip Type"])
data["Daily Summary"] = le.fit_transform(data["Daily Summary"])
data.corr()["Temperature (C)"]

C:\Users\sethp\AppData\Local\Temp\ipykernel_16840\2499864205.py:5: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()["Temperature (C)"]

Summary                     0.146658
Precip Type                -0.520381
Temperature (C)             1.000000
Apparent Temperature (C)    0.992629
Humidity                   -0.632255
Wind Speed (km/h)           0.008957
Wind Bearing (degrees)      0.029988
Visibility (km)             0.392847
Loud Cover                       NaN
Pressure (millibars)       -0.005447
Daily Summary               0.438879
Name: Temperature (C), dtype: float64

In [108]:
data.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,19,0,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,197
1,2006-04-01 01:00:00.000 +0200,19,0,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,197
2,2006-04-01 02:00:00.000 +0200,17,0,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,197
3,2006-04-01 03:00:00.000 +0200,19,0,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,197
4,2006-04-01 04:00:00.000 +0200,17,0,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,197

In [109]:
data=data[['Formatted Date','Summary','Precip Type','Humidity','Wind Speed (km/h)','Wind Bearing (degrees)','Visibility (km)','Pressure (millibars)','Temperature (C)']]

In [110]:
data.head()

,Formatted Date,Summary,Precip Type,Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Temperature (C)
0,2006-04-01 00:00:00.000 +0200,19,0,0.89,14.1197,251.0,15.8263,1015.13,9.472222
1,2006-04-01 01:00:00.000 +0200,19,0,0.86,14.2646,259.0,15.8263,1015.63,9.355556
2,2006-04-01 02:00:00.000 +0200,17,0,0.89,3.9284,204.0,14.9569,1015.94,9.377778
3,2006-04-01 03:00:00.000 +0200,19,0,0.83,14.1036,269.0,15.8263,1016.41,8.288889
4,2006-04-01 04:00:00.000 +0200,17,0,0.83,11.0446,259.0,15.8263,1016.51,8.755556

In [115]:
data['Formatted Date']=pd.to_datetime(data['Formatted Date'],utc=True).dt.hour
# data['Formatted Date']=data['Formatted Date'].dt.hour

In [118]:
data.head()

,Formatted Date,Summary,Precip Type,Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Temperature (C)
0,22,19,0,0.89,14.1197,251.0,15.8263,1015.13,9.472222
1,23,19,0,0.86,14.2646,259.0,15.8263,1015.63,9.355556
2,0,17,0,0.89,3.9284,204.0,14.9569,1015.94,9.377778
3,1,19,0,0.83,14.1036,269.0,15.8263,1016.41,8.288889
4,2,17,0,0.83,11.0446,259.0,15.8263,1016.51,8.755556

In [151]:
X = data.drop(columns =['Temperature (C)'])

In [152]:
scaler = MinMaxScaler(feature_range=(0, 1))
 
X["Summary"] = scaler.fit_transform(X[["Summary"]])
X["Humidity"] = scaler.fit_transform(X[["Humidity"]])
X["Wind Speed (km/h)"] = scaler.fit_transform(X[["Wind Speed (km/h)"]])
X["Wind Bearing (degrees)"] = scaler.fit_transform(X[["Wind Bearing (degrees)"]])
X["Visibility (km)"] = scaler.fit_transform(X[["Visibility (km)"]])
X["Pressure (millibars)"] = scaler.fit_transform(X[["Pressure (millibars)"]])

In [153]:
X.head()

,Formatted Date,Summary,Precip Type,Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars)
0,22,0.730769,0,0.89,0.221130,0.699164,0.983,0.970135
1,23,0.730769,0,0.86,0.223399,0.721448,0.983,0.970613
2,0,0.653846,0,0.89,0.061523,0.568245,0.929,0.970909
3,1,0.730769,0,0.83,0.220877,0.749304,0.983,0.971358
4,2,0.653846,0,0.83,0.172970,0.721448,0.983,0.971454

In [156]:
y=pd.DataFrame(data['Temperature (C)'])

In [160]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42,test_size=0.25,shuffle=True)

In [166]:
rf = RandomForestRegressor()
rf.fit(X_train,y_train)

C:\Users\sethp\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [167]:
y_pred = rf.predict(X_test)

In [169]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Calculate evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the evaluation metrics
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Absolute Error: 3.4723046017527848
Mean Squared Error: 20.81146339204942
R-squared: 0.7726760004588844